#ifndef __CONFIGURATIONS_H__
#define __CONFIGURATIONS_H__

/*CONFIGURATIONS ENABLES*/
#define NOT_DEBUGGING
//define I_SUPORT_FAST_DEMONSTRATION


/*MODULES ENABLES*/

#define UART_MODULE_ENABLE
#define RTC_MODULE_ENABLE
#define LCD_MODULE_ENABLE
#define LEDS_MODULE_ENABLE
#define SPEAKER_MODULE_ENABLE
#define  MOTOR_MODULE_ENABLE





#endif